### ISSUE TITLE
bottom overflowed by ~~ pixels

### ISSUE THREAD

**Issue by hschoi1** [beer-forest/beer-forest#4]
I am using SingleChildScrollView class but the overflow still exists (and the screen is not scrollable at all)
Am i missing any required settings? 

https://github.com/beer-forest/beer-forest/blob/313cbc1ab9887867812f7510bb31a8662c5c1ab1/lib/widget/user_form_widget.dart#L36 

![스크린샷 2021-08-27 오후 10 08 00](https://user-images.githubusercontent.com/40652625/131132161-68bd2468-8784-4c5b-b369-eb8f6bf498fa.png)

**Comment by jenriver** [comment]
hey mate,

you should wrap your columns / entire content in SingleChildScrollView. 
See ref here: https://stackoverflow.com/questions/49480051/flutter-dart-exceptions-caused-by-rendering-a-renderflex-overflowed

**Comment by hschoi1** [comment]
thx I wrapped AlertDialog in SingleChildScrollView and that did it! 
https://github.com/beer-forest/beer-forest/blob/381e0614a4c7e5bc4e0bf11132ccffb9a1bc95f4/lib/widget/add_user_dialog_widget.dart#L22
